# Generated by Django 5.2.3 on 2025-07-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_review_alter_place_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
